SQLITE_FILTER_LR = {
    "name": "SQLITE_FILTER_LR",
    "description": "Filter records from a large SQLite table using a SQL WHERE clause generated by the LLM",
    "example_questions": [
        "Records from results.db where score > 90",
        "Filter results table where status equals active",
        "Find entries in data.db where count exceeds 1000",
    ],
    "operators": ["SqliteFilter"],
    "output_type": "list[dict]",
}
